/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Categoria;
import Modelo.Habitacion;
import Modelo.Hotel;
import Modelo.Huesped;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author alexis
 */
public class admin_habitacion extends javax.swing.JDialog {

    /**
     * Creates new form admin_habitacion
     */
    int indicehabitacion = 0;
    String modo = "";
    DefaultListModel habitaciones;
    Controlador.Operaciones_hoteles oph = new Controlador.Operaciones_hoteles();
    Hotel hotel;

    public admin_habitacion(admin_hoteles parent, boolean modal, Hotel hotel) {
        super(parent, modal);
        initComponents();
        this.hotel = hotel;
        habitaciones = oph.mostrarHabitaciones(hotel.getIdhotel());
        activarjtxt(false);
        redimensionar();
        cargarencampos();
        botoneraNavegacionActivada(true);
        ponercontadores();
        jbejecutaraccion.setEnabled(false);
        activarcombos(false);
        jbcancelar.setEnabled(false);
        jbaltahuespedes.setEnabled(false);
        jbbajahuesped.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgmodo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtid = new javax.swing.JTextField();
        jtnombre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbmodo = new javax.swing.JLabel();
        rbalta = new javax.swing.JRadioButton();
        rbbaja = new javax.swing.JRadioButton();
        rbmodificacion = new javax.swing.JRadioButton();
        rbmodihuesped = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        btnPrime3 = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();
        btnUltim = new javax.swing.JButton();
        btnSig = new javax.swing.JButton();
        lblTot = new javax.swing.JLabel();
        lblReg = new javax.swing.JLabel();
        lbrgactual = new javax.swing.JLabel();
        lbtotal = new javax.swing.JLabel();
        cbh1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbh2 = new javax.swing.JComboBox();
        cbh3 = new javax.swing.JComboBox();
        cbh4 = new javax.swing.JComboBox();
        cbh5 = new javax.swing.JComboBox();
        jbejecutaraccion = new javax.swing.JButton();
        lbidhabitacion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbnumcamas = new javax.swing.JComboBox();
        jtidhabitacion = new javax.swing.JTextField();
        jbaltahuespedes = new javax.swing.JButton();
        jbbajahuesped = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de Habitaciones");
        jLabel1.setOpaque(true);

        jLabel2.setText("Id Hotel");

        jLabel4.setText("Nombre Hotel");

        jtid.setEditable(false);

        jtnombre.setEditable(false);
        jtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnombreActionPerformed(evt);
            }
        });

        lbmodo.setText("Modo");

        bgmodo.add(rbalta);
        rbalta.setText("Alta");
        rbalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbaltaActionPerformed(evt);
            }
        });

        bgmodo.add(rbbaja);
        rbbaja.setText("Baja");
        rbbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbajaActionPerformed(evt);
            }
        });

        bgmodo.add(rbmodificacion);
        rbmodificacion.setText("Modificacion");
        rbmodificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmodificacionActionPerformed(evt);
            }
        });

        bgmodo.add(rbmodihuesped);
        rbmodihuesped.setText("Modificar Huespedes");
        rbmodihuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmodihuespedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbbaja)
                                    .addComponent(rbalta)
                                    .addComponent(rbmodificacion))
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbmodo)
                                .addGap(100, 100, 100))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbmodihuesped)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbmodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbalta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbbaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbmodificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbmodihuesped)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPrime3.setText("|<");
        btnPrime3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrime3ActionPerformed(evt);
            }
        });

        btnAnt.setText("<<");
        btnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntActionPerformed(evt);
            }
        });

        btnUltim.setText(">|");
        btnUltim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimActionPerformed(evt);
            }
        });

        btnSig.setText(">>");
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });

        lblTot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTot.setText("Tot. registros");
        lblTot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReg.setText("Reg. actual");
        lblReg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbrgactual.setText("0");

        lbtotal.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrime3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTot, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(lblReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbrgactual)
                    .addComponent(lbtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSig, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUltim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrime3)
                    .addComponent(btnAnt)
                    .addComponent(btnUltim)
                    .addComponent(btnSig)
                    .addComponent(lblReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbrgactual))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbtotal))
                .addContainerGap())
        );

        cbh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbh1ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Huespedes");
        jLabel5.setOpaque(true);

        cbh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbh2ActionPerformed(evt);
            }
        });

        cbh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbh3ActionPerformed(evt);
            }
        });

        cbh4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbh4ActionPerformed(evt);
            }
        });

        cbh5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbh5ActionPerformed(evt);
            }
        });

        jbejecutaraccion.setText("Ejecutar Accion");
        jbejecutaraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbejecutaraccionActionPerformed(evt);
            }
        });

        lbidhabitacion.setText("Id Habitacion");

        jLabel3.setText("Nº Camas");

        cbnumcamas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        jtidhabitacion.setEditable(false);

        jbaltahuespedes.setText("Alta Huespedes");
        jbaltahuespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaltahuespedesActionPerformed(evt);
            }
        });

        jbbajahuesped.setText("Baja Huespedes");
        jbbajahuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbajahuespedActionPerformed(evt);
            }
        });

        jbcancelar.setText("Cancelar");
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(lbidhabitacion)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbnumcamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtidhabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtid, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbh2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbbajahuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbh1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbaltahuespedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbh4, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbh5, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbh3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jbejecutaraccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbidhabitacion)
                            .addComponent(jtidhabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbnumcamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbejecutaraccion)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbaltahuespedes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbbajahuesped))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbh3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbcancelar))
                .addGap(18, 18, 18)
                .addComponent(cbh4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbh5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnombreActionPerformed

    private void rbaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbaltaActionPerformed

        indicehabitacion = 0;
        modo = "Alta";
        jbejecutaraccion.setEnabled(true);
        botoneraNavegacionActivada(false);
        jtidhabitacion.setText("-");
        //activarjtxt(true);
        cbnumcamas.setEnabled(true);
        lbrgactual.setText("-");
        lbtotal.setText("-");
        jbcancelar.setEnabled(false);
        jbaltahuespedes.setEnabled(false);
        jbbajahuesped.setEnabled(false);
        activarcombos(false);
        cbnumcamas.setSelectedIndex(0);

    }//GEN-LAST:event_rbaltaActionPerformed

    private void rbbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbajaActionPerformed
        cargarencampos();
        botoneraNavegacionActivada(true);
        modo = "Baja";
        ponercontadores();
        activarjtxt(false);
        jbejecutaraccion.setEnabled(true);
        jbcancelar.setEnabled(false);
        jbaltahuespedes.setEnabled(false);
        jbbajahuesped.setEnabled(false);
        activarcombos(false);

    }//GEN-LAST:event_rbbajaActionPerformed

    private void rbmodificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmodificacionActionPerformed
        activarcombos(false);
        modo = "Modi";
        cargarencampos();
        botoneraNavegacionActivada(true);
        ponercontadores();
        activarjtxt(false);
        this.cbnumcamas.setEnabled(true);
        jbejecutaraccion.setEnabled(true);
        jbcancelar.setEnabled(false);
        jbaltahuespedes.setEnabled(false);
        jbbajahuesped.setEnabled(false);

    }//GEN-LAST:event_rbmodificacionActionPerformed

    private void btnPrime3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrime3ActionPerformed
        indicehabitacion = 0;
        limpiarcombos();
        btnPrime3.setEnabled(false);
        btnAnt.setEnabled(false);
        btnSig.setEnabled(true);
        btnUltim.setEnabled(true);
        cargarencampos();
        ponercontadores();

    }//GEN-LAST:event_btnPrime3ActionPerformed

    private void btnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntActionPerformed
        indicehabitacion--;
        if (indicehabitacion < 0) {
            btnPrime3.setEnabled(false);
            btnAnt.setEnabled(false);
            btnSig.setEnabled(true);
            btnUltim.setEnabled(true);
            indicehabitacion = 0;

        } else {
            btnPrime3.setEnabled(true);
            btnAnt.setEnabled(true);
            btnSig.setEnabled(true);
            btnUltim.setEnabled(true);
            limpiarcombos();
            cargarencampos();
        }
        ponercontadores();
    }//GEN-LAST:event_btnAntActionPerformed

    private void btnUltimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimActionPerformed
        indicehabitacion = habitaciones.size() - 1;
        limpiarcombos();
        btnPrime3.setEnabled(true);
        btnAnt.setEnabled(true);
        btnSig.setEnabled(false);
        btnUltim.setEnabled(false);
        cargarencampos();
        ponercontadores();
    }//GEN-LAST:event_btnUltimActionPerformed

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed

        indicehabitacion++;
        if (indicehabitacion > habitaciones.size() - 1) {
            btnPrime3.setEnabled(true);
            btnAnt.setEnabled(true);
            btnSig.setEnabled(false);
            btnUltim.setEnabled(false);
            indicehabitacion = habitaciones.size() - 1;

        } else {
            btnPrime3.setEnabled(true);
            btnAnt.setEnabled(true);
            btnSig.setEnabled(true);
            btnUltim.setEnabled(true);
            limpiarcombos();
            cargarencampos();

        }

        ponercontadores();
    }//GEN-LAST:event_btnSigActionPerformed

    private void jbejecutaraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbejecutaraccionActionPerformed
        int ax = JOptionPane.showConfirmDialog(null, "Estas seguro de ejecutar la accion?");
        if (ax == JOptionPane.YES_OPTION) {
            switch (modo) {
                case "Alta":
                    if (!comprobarDatos()) {
                        Habitacion habitacion = new Habitacion(hotel, Integer.parseInt(String.valueOf(cbnumcamas.getSelectedItem())), null);
                        oph.altaHabitacion(habitacion);
                        habitaciones = oph.mostrarHabitaciones(hotel.getIdhotel());
                    }

                    cbnumcamas.setSelectedIndex(0);

                    break;
                case "Baja":

                    Habitacion habitacion = (Habitacion) habitaciones.get(indicehabitacion);

                    oph.bajaHabitacion(habitacion);
                    habitaciones = oph.mostrarHabitaciones(hotel.getIdhotel());
                    indicehabitacion = 0;
                    cargarencampos();
                    ponercontadores();
                    botoneraNavegacionActivada(true);

                    break;
                case "Modi":

                    if (!comprobarDatos()) {
                        Habitacion habitacion1 = (Habitacion) habitaciones.get(indicehabitacion);
                        habitacion1.setNumcamas(Integer.parseInt(String.valueOf(cbnumcamas.getSelectedItem())));
                        oph.ModiHabitacion(habitacion1);
                        habitaciones = oph.mostrarHabitaciones(hotel.getIdhotel());

                    }

                    break;
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se han realizado cambios en la base de datos");
        }
    }//GEN-LAST:event_jbejecutaraccionActionPerformed

    private void rbmodihuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmodihuespedActionPerformed
        modo = "ModiHuesped";
        activarjtxt(false);
        botoneraNavegacionActivada(false);
//        jbcancelar.setEnabled(true);
//        jbaltahuespedes.setEnabled(true);
//        jbbajahuesped.setEnabled(true);
        cargarencampos();

        rbalta.setEnabled(false);
        rbbaja.setEnabled(false);
        rbmodificacion.setEnabled(false);
        rbmodihuesped.setEnabled(false);


    }//GEN-LAST:event_rbmodihuespedActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed
        jbcancelar.setEnabled(false);
        jbaltahuespedes.setEnabled(false);
        jbbajahuesped.setEnabled(false);
        rbalta.setEnabled(true);
        rbbaja.setEnabled(true);
        rbmodificacion.setEnabled(true);
        rbmodihuesped.setEnabled(true);
        rbmodificacionActionPerformed(null);
        rbmodificacion.setSelected(true);
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jbaltahuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaltahuespedesActionPerformed
        int ax = JOptionPane.showConfirmDialog(null, "Estas seguro de ejecutar la accion?");
        if (ax == JOptionPane.YES_OPTION) {
            modo = "";
            jbcancelar.setEnabled(false);
            jbaltahuespedes.setEnabled(false);
            jbbajahuesped.setEnabled(false);
            rbalta.setEnabled(true);
            rbbaja.setEnabled(true);
            rbmodificacion.setEnabled(true);
            rbmodihuesped.setEnabled(true);
            activarcombos(false);
            if (cbh1.getItemCount() != 0) {
                if (!cbh1.getSelectedItem().toString().equals("")) {
                    String[] combosplit = String.valueOf(cbh1.getSelectedItem()).split("-");
                    Huesped h = oph.buscarHuesped(combosplit[0]);
                    h.setHabitacion((Habitacion) habitaciones.get(indicehabitacion));
                    oph.ModiHuesped(h);
                }
            }
            if (cbh2.getItemCount() != 0) {
                if (!cbh2.getSelectedItem().toString().equals("")) {
                    String[] combosplit = String.valueOf(cbh2.getSelectedItem()).split("-");
                    Huesped h = oph.buscarHuesped(combosplit[0]);
                    h.setHabitacion((Habitacion) habitaciones.get(indicehabitacion));
                    oph.ModiHuesped(h);
                }
            }
            if (cbh3.getItemCount() != 0) {
                if (!cbh3.getSelectedItem().toString().equals("")) {
                    String[] combosplit = String.valueOf(cbh3.getSelectedItem()).split("-");
                    Huesped h = oph.buscarHuesped(combosplit[0]);
                    h.setHabitacion((Habitacion) habitaciones.get(indicehabitacion));
                    oph.ModiHuesped(h);
                }
            }
            if (cbh4.getItemCount() != 0) {
                if (!cbh4.getSelectedItem().toString().equals("")) {
                    String[] combosplit = String.valueOf(cbh4.getSelectedItem()).split("-");
                    Huesped h = oph.buscarHuesped(combosplit[0]);
                    h.setHabitacion((Habitacion) habitaciones.get(indicehabitacion));
                    oph.ModiHuesped(h);
                }
            }
            if (cbh5.getItemCount() != 0) {
                if (!cbh5.getSelectedItem().toString().equals("")) {
                    String[] combosplit = String.valueOf(cbh5.getSelectedItem()).split("-");
                    Huesped h = oph.buscarHuesped(combosplit[0]);
                    h.setHabitacion((Habitacion) habitaciones.get(indicehabitacion));
                    oph.ModiHuesped(h);
                }
            }
            JOptionPane.showMessageDialog(null, "Alta correcta.");
            rbmodificacionActionPerformed(null);
            rbmodificacion.setSelected(true);

        } else {
            JOptionPane.showMessageDialog(null, "No se han realizado cambios en la base de datos");
        }


    }//GEN-LAST:event_jbaltahuespedesActionPerformed

    private void jbbajahuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbajahuespedActionPerformed
        int ax = JOptionPane.showConfirmDialog(null, "Estas seguro de ejecutar la accion?");
        if (ax == JOptionPane.YES_OPTION) {

            Habitacion habitacion = (Habitacion) habitaciones.get(indicehabitacion);
            DefaultListModel huespedes = oph.mostrarHuespedes(habitacion.getIdhabitacion());
            for (int i = 0; i < huespedes.size(); i++) {
                Huesped h = (Huesped) huespedes.get(i);
                h.setHabitacion(null);
                oph.ModiHuesped(h);
            }
            meterencombo(habitacion);
            JOptionPane.showMessageDialog(null, "Borrado correctamente.");
            activarcombos(false);

            jbcancelar.setEnabled(false);
            jbaltahuespedes.setEnabled(false);
            jbbajahuesped.setEnabled(false);
            rbalta.setEnabled(true);
            rbbaja.setEnabled(true);
            rbmodificacion.setEnabled(true);
            rbmodihuesped.setEnabled(true);
            rbmodificacionActionPerformed(null);
            rbmodificacion.setSelected(true);
        } else {
            JOptionPane.showMessageDialog(null, "No se han realizado cambios en la base de datos");
        }


    }//GEN-LAST:event_jbbajahuespedActionPerformed

    private void cbh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbh1ActionPerformed

        String tosplit = cbh1.getSelectedItem().toString();
        String[] split = tosplit.split("-");
        if (!split[0].equals("")) {
            Huesped h = oph.buscarHuesped(split[0]);
            if (h.getIndividual().equals('S')) {
                if (modo.equals("ModiHuesped")) {
                    cbh1.setEnabled(true);
                    cbh2.setEnabled(false);
                    cbh3.setEnabled(false);
                    cbh4.setEnabled(false);
                    cbh5.setEnabled(false);

                    if (cbh2.getItemCount() != 0) {
                        cbh2.setSelectedIndex(cbh2.getItemCount() - 1);
                    }

                    if (cbh3.getItemCount() != 0) {
                        cbh3.setSelectedIndex(cbh3.getItemCount() - 1);
                    }

                    if (cbh4.getItemCount() != 0) {
                        cbh4.setSelectedIndex(cbh4.getItemCount() - 1);
                    }

                    if (cbh5.getItemCount() != 0) {
                        cbh5.setSelectedIndex(cbh5.getItemCount() - 1);
                    }

                }
            } else {
                activarhuespedes();
            }

        }
    }//GEN-LAST:event_cbh1ActionPerformed

    private void cbh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbh2ActionPerformed

        String tosplit = cbh2.getSelectedItem().toString();
        String[] split = tosplit.split("-");
        if (!split[0].equals("")) {
            Huesped h = oph.buscarHuesped(split[0]);
            if (h.getIndividual().equals('S')) {
                if (modo.equals("ModiHuesped")) {
                    cbh1.setEnabled(false);
                    cbh2.setEnabled(true);
                    cbh3.setEnabled(false);
                    cbh4.setEnabled(false);
                    cbh5.setEnabled(false);

                    if (cbh1.getItemCount() != 0) {
                        cbh1.setSelectedIndex(cbh1.getItemCount() - 1);
                    }

                    if (cbh3.getItemCount() != 0) {
                        cbh3.setSelectedIndex(cbh3.getItemCount() - 1);
                    }

                    if (cbh4.getItemCount() != 0) {
                        cbh4.setSelectedIndex(cbh4.getItemCount() - 1);
                    }

                    if (cbh5.getItemCount() != 0) {
                        cbh5.setSelectedIndex(cbh5.getItemCount() - 1);
                    }
                }
            } else {
                activarhuespedes();
            }
        }

    }//GEN-LAST:event_cbh2ActionPerformed

    private void cbh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbh3ActionPerformed

        String tosplit = cbh3.getSelectedItem().toString();
        String[] split = tosplit.split("-");
        if (!split[0].equals("")) {
            Huesped h = oph.buscarHuesped(split[0]);
            if (h.getIndividual().equals('S')) {
                if (modo.equals("ModiHuesped")) {
                    cbh1.setEnabled(false);
                    cbh2.setEnabled(false);
                    cbh3.setEnabled(true);
                    cbh4.setEnabled(false);
                    cbh5.setEnabled(false);
                    if (cbh1.getItemCount() != 0) {
                        cbh1.setSelectedIndex(cbh1.getItemCount() - 1);
                    }

                    if (cbh2.getItemCount() != 0) {
                        cbh2.setSelectedIndex(cbh2.getItemCount() - 1);
                    }

                    if (cbh4.getItemCount() != 0) {
                        cbh4.setSelectedIndex(cbh4.getItemCount() - 1);
                    }

                    if (cbh5.getItemCount() != 0) {
                        cbh5.setSelectedIndex(cbh5.getItemCount() - 1);
                    }
                }
            } else {
                activarhuespedes();
            }

        }
    }//GEN-LAST:event_cbh3ActionPerformed

    private void cbh4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbh4ActionPerformed

        String tosplit = cbh4.getSelectedItem().toString();
        String[] split = tosplit.split("-");
        if (!split[0].equals("")) {
            Huesped h = oph.buscarHuesped(split[0]);
            if (h.getIndividual().equals('S')) {
                if (modo.equals("ModiHuesped")) {
                    cbh1.setEnabled(false);
                    cbh2.setEnabled(false);
                    cbh3.setEnabled(false);
                    cbh4.setEnabled(true);
                    cbh5.setEnabled(false);
                    if (cbh1.getItemCount() != 0) {
                        cbh1.setSelectedIndex(cbh1.getItemCount() - 1);
                    }

                    if (cbh2.getItemCount() != 0) {
                        cbh2.setSelectedIndex(cbh2.getItemCount() - 1);
                    }

                    if (cbh3.getItemCount() != 0) {
                        cbh3.setSelectedIndex(cbh3.getItemCount() - 1);
                    }

                    if (cbh5.getItemCount() != 0) {
                        cbh5.setSelectedIndex(cbh5.getItemCount() - 1);
                    }
                }
            } else {
                activarhuespedes();

            }
        }
    }//GEN-LAST:event_cbh4ActionPerformed

    private void cbh5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbh5ActionPerformed

        String tosplit = cbh5.getSelectedItem().toString();
        String[] split = tosplit.split("-");
        if (!split[0].equals("")) {
            Huesped h = oph.buscarHuesped(split[0]);
            if (h.getIndividual().equals('S')) {
                if (modo.equals("ModiHuesped")) {
                    cbh1.setEnabled(false);
                    cbh2.setEnabled(false);
                    cbh3.setEnabled(false);
                    cbh4.setEnabled(false);
                    cbh5.setEnabled(true);
                    if (cbh1.getItemCount() != 0) {
                        cbh1.setSelectedIndex(cbh1.getItemCount() - 1);
                    }

                    if (cbh2.getItemCount() != 0) {
                        cbh2.setSelectedIndex(cbh2.getItemCount() - 1);
                    }

                    if (cbh3.getItemCount() != 0) {
                        cbh3.setSelectedIndex(cbh3.getItemCount() - 1);
                    }

                    if (cbh4.getItemCount() != 0) {
                        cbh4.setSelectedIndex(cbh4.getItemCount() - 1);
                    }

                }
            } else {
                activarhuespedes();
            }

        }
    }//GEN-LAST:event_cbh5ActionPerformed
    private void botoneraNavegacionActivada(boolean estado) {
        btnPrime3.setEnabled(estado);
        btnAnt.setEnabled(estado);
        btnSig.setEnabled(estado);
        btnUltim.setEnabled(estado);
    }

    private void activarjtxt(Boolean estado) {
        jtid.setEnabled(estado);
        jtnombre.setEnabled(estado);
        cbnumcamas.setEnabled(estado);
        jtidhabitacion.setEnabled(estado);
    }

    private void ponercontadores() {
        lbrgactual.setText(String.valueOf(indicehabitacion + 1));
        lbtotal.setText(String.valueOf(habitaciones.size()));
    }

    private void cargarencampos() {
        if (habitaciones.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay datos en la base de datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            dispose();
        } else {
            Habitacion habitacion = (Habitacion) habitaciones.get(indicehabitacion);
            jtid.setText(String.valueOf(hotel.getIdhotel()));
            jtnombre.setText(hotel.getNombre());
            jtidhabitacion.setText(habitacion.getIdhabitacion().toString());
            for (int i = 0; i < cbnumcamas.getItemCount(); i++) {
                cbnumcamas.setSelectedIndex(i);
                String[] combosplit = String.valueOf(cbnumcamas.getSelectedItem()).split("-");
                if (combosplit[0].equals(String.valueOf(habitacion.getNumcamas()))) {
                    break;
                }
            }
            //meterencombo(habitacion.getIdhabitacion());
            meterencombo(habitacion);
            if (modo.equals("ModiHuesped")) {
                activarhuespedes();
            }

        }

    }

    private boolean comprobarDatos() {
        boolean comprobacion = false;
        String error = "Hay errores en : \n";
        if (jtnombre.getText().length() == 0) {
            error = error + "error en el campo nombre \n";
            comprobacion = true;
        }
        if (jtid.getText().length() == 0) {
            error = error + "error en el campo id \n";
            comprobacion = true;
        }

        return comprobacion;
    }

    private void activarhuespedes() {
        if (modo != null) {
            if (modo.equals("ModiHuesped")) {
                switch (Integer.parseInt(String.valueOf(cbnumcamas.getSelectedItem()))) {
                    case 1:
                        cbh1.setEnabled(true);
                        cbh2.setEnabled(false);
                        cbh3.setEnabled(false);
                        cbh4.setEnabled(false);
                        cbh5.setEnabled(false);
                        break;
                    case 2:
                        cbh1.setEnabled(true);
                        cbh2.setEnabled(true);
                        cbh3.setEnabled(false);
                        cbh4.setEnabled(false);
                        cbh5.setEnabled(false);
                        break;
                    case 3:
                        cbh1.setEnabled(true);
                        cbh2.setEnabled(true);
                        cbh3.setEnabled(true);
                        cbh4.setEnabled(false);
                        cbh5.setEnabled(false);
                        break;
                    case 4:
                        cbh1.setEnabled(true);
                        cbh2.setEnabled(true);
                        cbh3.setEnabled(true);
                        cbh4.setEnabled(true);
                        cbh5.setEnabled(false);
                        break;
                    case 5:
                        cbh1.setEnabled(true);
                        cbh2.setEnabled(true);
                        cbh3.setEnabled(true);
                        cbh4.setEnabled(true);
                        cbh5.setEnabled(true);
                        break;
                }
            }
        }
    }

    private void activarcombos(boolean estado) {
        cbh1.setEnabled(estado);
        cbh2.setEnabled(estado);
        cbh3.setEnabled(estado);
        cbh4.setEnabled(estado);
        cbh5.setEnabled(estado);
    }

    private void meterencombo(Habitacion habitacion) {

        int maximo = 0;
        DefaultListModel huespedes = oph.mostrarHuespedes(habitacion.getIdhabitacion());
        if (huespedes.isEmpty()) {
            if (huespedes.size() < habitacion.getNumcamas()) {
                if (modo.equals("ModiHuesped")) {
                    jbcancelar.setEnabled(true);
                    jbaltahuespedes.setEnabled(true);
                    jbbajahuesped.setEnabled(false);
                }
                huespedes = oph.mostrarHuespedes();
                ArrayList<String> ven = new ArrayList<String>();
                String anadircb;
                for (int i = 0; i < huespedes.size(); i++) {
                    Huesped h = (Huesped) huespedes.get(i);
                    anadircb = h.getDni() + "-" + h.getNombre() + "," + h.getApellidos();
                    ven.add(anadircb);
                }
                ven.add("");
                cbh1.setModel(new DefaultComboBoxModel(ven.toArray()));
                cbh2.setModel(new DefaultComboBoxModel(ven.toArray()));
                cbh3.setModel(new DefaultComboBoxModel(ven.toArray()));
                cbh4.setModel(new DefaultComboBoxModel(ven.toArray()));
                cbh5.setModel(new DefaultComboBoxModel(ven.toArray()));
                cbh1.setSelectedIndex(cbh1.getItemCount() - 1);
                cbh2.setSelectedIndex(cbh1.getItemCount() - 1);
                cbh3.setSelectedIndex(cbh1.getItemCount() - 1);
                cbh4.setSelectedIndex(cbh1.getItemCount() - 1);
                cbh5.setSelectedIndex(cbh1.getItemCount() - 1);
            }
        } else {
            if (modo.equals("ModiHuesped")) {
                jbcancelar.setEnabled(true);
                jbaltahuespedes.setEnabled(false);
                jbbajahuesped.setEnabled(true);
            }
            ArrayList<String> ven = new ArrayList<String>();
            String anadircb;
            for (int i = 0; i < huespedes.size(); i++) {
                Huesped h = (Huesped) huespedes.get(i);
                anadircb = h.getDni() + "-" + h.getNombre() + "," + h.getApellidos();
                ven.add(anadircb);
            }
            if (huespedes.size() > 0) {
                if (huespedes.get(0) != null) {
                    cbh1.setModel(new DefaultComboBoxModel(ven.toArray()));
                    cbh1.setSelectedIndex(0);
                    maximo = 1;
                    if (maximo < huespedes.size()) {
                        cbh2.setModel(new DefaultComboBoxModel(ven.toArray()));
                        cbh2.setSelectedIndex(1);
                        maximo = 2;
                        if (maximo < huespedes.size()) {
                            maximo = 3;
                            cbh3.setModel(new DefaultComboBoxModel(ven.toArray()));
                            cbh3.setSelectedIndex(2);
                            if (maximo < huespedes.size()) {
                                cbh4.setModel(new DefaultComboBoxModel(ven.toArray()));
                                cbh4.setSelectedIndex(3);
                                maximo = 4;
                                if (maximo < huespedes.size()) {
                                    cbh5.setModel(new DefaultComboBoxModel(ven.toArray()));
                                    cbh5.setSelectedIndex(4);
                                }
                            }
                        }
                    }
                }
            } else {
                cbh1.setModel(new DefaultComboBoxModel());
                cbh2.setModel(new DefaultComboBoxModel());
                cbh3.setModel(new DefaultComboBoxModel());
                cbh4.setModel(new DefaultComboBoxModel());
                cbh5.setModel(new DefaultComboBoxModel());

            }

        }
    }

    private void limpiarcombos() {
        cbh1.setModel(new DefaultComboBoxModel());
        cbh2.setModel(new DefaultComboBoxModel());
        cbh3.setModel(new DefaultComboBoxModel());
        cbh4.setModel(new DefaultComboBoxModel());
        cbh5.setModel(new DefaultComboBoxModel());
    }

    private void redimensionar() {

        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int ancho = 2 * d.width / 3;
        int alto = d.height / 2;
        this.setLocationRelativeTo(this);
        d = Toolkit.getDefaultToolkit().getScreenSize();
        ancho = 2 * d.width / 6;
        alto = d.height / 4;
        this.setMaximumSize(new Dimension(ancho, alto));
        this.setMinimumSize(new Dimension(ancho, alto));
        this.pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgmodo;
    private javax.swing.JButton btnAnt;
    private javax.swing.JButton btnPrime3;
    private javax.swing.JButton btnSig;
    private javax.swing.JButton btnUltim;
    private javax.swing.JComboBox cbh1;
    private javax.swing.JComboBox cbh2;
    private javax.swing.JComboBox cbh3;
    private javax.swing.JComboBox cbh4;
    private javax.swing.JComboBox cbh5;
    private javax.swing.JComboBox cbnumcamas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbaltahuespedes;
    private javax.swing.JButton jbbajahuesped;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbejecutaraccion;
    private javax.swing.JTextField jtid;
    private javax.swing.JTextField jtidhabitacion;
    private javax.swing.JTextField jtnombre;
    private javax.swing.JLabel lbidhabitacion;
    private javax.swing.JLabel lblReg;
    private javax.swing.JLabel lblTot;
    private javax.swing.JLabel lbmodo;
    private javax.swing.JLabel lbrgactual;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JRadioButton rbalta;
    private javax.swing.JRadioButton rbbaja;
    private javax.swing.JRadioButton rbmodificacion;
    private javax.swing.JRadioButton rbmodihuesped;
    // End of variables declaration//GEN-END:variables

}
